version: '3.8'

services:
  base:
    build:
      context: docker
      args:
        DOCKER_BUILDKIT: 1
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
        HOST_USER: $HOST_USER
        PROJECT_MOUNT_PATH: $PROJECT_MOUNT_PATH
    user: $HOST_UID:$HOST_GID
    volumes: 
      - .:$PROJECT_MOUNT_PATH
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.ssh:/home/$HOST_USER/.ssh
    working_dir: $PROJECT_MOUNT_PATH
    environment:
      # For GUI program
      DISPLAY: $DISPLAY 
      NVIDIA_DRIVER_CAPABILITIES: all
      # for bash
      PROJECT_PATH: $PWD
      PROJECT_MOUNT_PATH: $PROJECT_MOUNT_PATH
      TERM: xterm-256color
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    ipc: host

  host:
    extends: base
    build:
      args:
        BASE_IMAGE: ubuntu:20.04
